---
abstract: 'Tags helper for Oracle tree manager.'
author:
  - 'Michal Josef Spacek <skim@cpan.org>'
build_requires:
  English: 0
  Error::Pure::Utils: 0
  ExtUtils::MakeMaker: 6.36
  Tags::Output::Raw: 0
  Test::MockObject: 0
  Test::More: 0
  Test::NoWarnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.21'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Tags-HTML-Tree-Oracle
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Class::Utils: 0.02
  Error::Pure: 0.07
  Scalar::Util: 0
  Tags::HTML: 0
  perl: 5.8.0
resources:
  bugtracker: https://github.com/michal-josef-spacek/Tags-HTML-Tree-Oracle/issues
  homepage: https://github.com/michal-josef-spacek/Tags-HTML-Tree-Oracle
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/michal-josef-spacek/Tags-HTML-Tree-Oracle
version: '0.01'
